import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   return (
    <html lang="en">
      <body>
        {/* Header which is shared across all routes*/}
        <header>Header</header>
        {children}
        {/* Footer which is shared across all routes*/}
        <footer>Footer</footer>
      </body>
    </html>
  );
}

